baseURL = 'https://bsmuga.github.io/'
languageCode = 'en-us'
title = "B'log"
theme = 'hermit-v2'

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 20
  
[caches]
  [caches.images]
    dir = ':cacheDir/images'
